DELETE FROM `control_vehicular` WHERE `control_vehicular`.`ID_CONTROL` = '00001';
DELETE FROM `control_vehicular` WHERE `control_vehicular`.`ID_CONTROL` = '00002';
DELETE FROM `control_vehicular` WHERE `control_vehicular`.`ID_CONTROL` = '00003';




SELECT emp.ID_EMPLEADO, emp.EMP_APELLIDOS, emp.EMP_NOMBRES, emp.DOC_IDENTIDAD, par.PARAM_DESCRIPCION AS SEXO, emp.EMP_EMAIL, emp.EMP_TELEFONO, emp.FECHA_NAC, emp.FECHA_REG, emp.EMP_ESTADO FROM dt_empleados emp INNER JOIN dt_parametros par ON emp.EMP_SEXO=par.ID_PARAMETRO


ALTER TABLE `dt_usuarios` CHANGE `id_usuario` `ID_USUARIO` CHAR(5) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `id_persona` `ID_EMPLEADO` CHAR(5) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `id_sede` `ID_SEDE` CHAR(5) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `id_nivel` `ID_NIVEL` CHAR(5) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `usuario` `USUARIO` VARCHAR(25) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `pass` `PASS` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `fecha_registro` `FECHA_REG` VARCHAR(12) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `estado_usuario` `USUARIO_ESTADO` CHAR(2) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL, CHANGE `CONTROL_ESTADO` `CONTROL_ESTADO` CHAR(2) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL;


SELECT us.ID_USUARIO, emp.EMP_APELLIDOS, emp.EMP_NOMBRES FROM dt_usuarios us INNER JOIN dt_empleados emp ON us.ID_EMPLEADO=emp.ID_EMPLEADO

SELECT us.ID_USUARIO, emp.EMP_APELLIDOS, emp.EMP_NOMBRES,us.SEDE, par.PARAM_DESCRIPCION, us.USUARIO, us.PASS, us.FECHA_REG, us.USUARIO_ESTADO FROM dt_usuarios us INNER JOIN dt_empleados emp ON us.ID_EMPLEADO=emp.ID_EMPLEADO INNER JOIN dt_parametros par ON us.ID_NIVEL=par.ID_PARAMETRO

SELECT * FROM control_vehicular WHERE F_REGISTRO_S BETWEEN '2018-05-15 ' AND '2018-05-17 '

SELECT us.USUARIO, us.PASS, par.PARAM_DESCRIPCION FROM dt_usuarios us INNER JOIN dt_parametros par ON par.ID_PARAMETRO = us.ID_NIVEL


SELECT MONTH(F_REGISTRO_S) AS MES 
FROM control_vehicular
GROUP BY MONTH(F_REGISTRO_S)
ORDER BY F_REGISTRO_S ASC


/*ESTADISTICA */


SELECT MONTH(F_REGISTRO_S) AS MES, YEAR(F_REGISTRO_S) AS ANIO, COUNT(MONTH(F_REGISTRO_S)) AS SALIDAS FROM control_vehicular GROUP BY MONTH(F_REGISTRO_S)


/*
PDF */

SELECT cv.ID_CONTROL, cv.N_PLACA, cv.KILOMETRAJE, cv.KILOMETRAJE_FN, emp.EMP_NOMBRES, emp.EMP_APELLIDOS, cv.L_ORIGEN, cv.L_DESTINO, cv.F_REGISTRO_S, cv.HORA_S, cv.F_REGISTRO_I, cv.ACTIVIDADES FROM control_vehicular cv INNER JOIN dt_empleados emp ON emp.ID_EMPLEADO=cv.ID_USUARIO